name: wbseg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.23,<2.0
  - matplotlib>=3.7
  - scipy>=1.10
  - scikit-image>=0.20
  - opencv>=4.8
  - pip
  - pip:
      - tensorflow>=2.13,<2.16
      - keras>=2.13,<2.16
      - pycocotools>=2.0.7
